spring:
  profiles:
    active: local

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://leeki-test.mysql.database.azure.com:3306/shop
    username: dlrlgodsha
    password: dkdlzks12@
    driver-class-name: com.mysql.cj.jdbc.Driver

  session:
    store-type: jdbc

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

  web:
    cors:
      mappings:
        '[/api/**]':
          allowed-origins: "http://localhost:5173"
          allowed-methods: "GET,POST,PUT,DELETE"
          allow-credentials: true

  # 로그 레벨 추가
  logging:
    level:
      root: INFO
      org.springframework.web: DEBUG
      org.springframework.security: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE # 쿼리 파라미터 로그
      com.apple.shop: DEBUG  # ← 본인 패키지

server:
  port: 5000
  servlet:
    session:
      timeout: 30m

cors-allowed-orgins: http://localhost:5173