spring:
  datasource:
    url: jdbc:mysql://leeki-test.mysql.database.azure.com:3306/shop
    username: dlrlgodsha
    password: dkdlzks12@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: update

  web:
    cors:
      mappings:
        '[/api/**]':
          allowed-origins: "http://localhost:5173"
          allowed-methods: "GET,POST,PUT,DELETE"

server:
  port: 8091